// Automatically generated file, do not edit!

#pragma once
#include "mir/mir.hpp"

#define RISCV_NAMESPACE_BEGIN namespace mir::RISCV {
#define RISCV_NAMESPACE_END }

RISCV_NAMESPACE_BEGIN
enum RISCVInst {
    RISCVInstBegin = ISASpecificBegin,
    
            ADD_UW,
            ANDN,
            ORN,
            XNOR,
            MIN,
            MAX,
            MINU,
            MAXU,
            DIVUW,
            REMUW,
            SLLW,
            SRLW,
            SRAW,
            SLLI_UW,
            ADDIW,
            BEQ,
            BNE,
            BLE,
            BGT,
            BLT,
            BGE,
            BLEU,
            BGTU,
            BLTU,
            BGEU,
            FADD_S,
            FSUB_S,
            FMUL_S,
            FDIV_S,
            FMIN_S,
            FMAX_S,
            FMADD_S,
            FMSUB_S,
            FNMADD_S,
            FNMSUB_S,
            FNEG_S,
            FABS_S,
            FMV_S,
            FSQRT_S,
            FSGNJ_S,
            FCLASS_S,
            FMV_X_W,
            FCVT_WU_S,
            FMV_W_X,
            FCVT_S_W,
            FCVT_S_WU,
            FEQ_S,
            FLT_S,
            FLE_S,
            FCVT_W_S,
            ADD,
            ADDW,
            SUB,
            SUBW,
            XOR,
            OR,
            AND,
            SLL,
            SRL,
            SRA,
            SLT,
            SLTU,
            ADDI,
            XORI,
            ORI,
            ANDI,
            SLTI,
            SLTIU,
            SLLI,
            SRLI,
            SRAI,
            SLLIW,
            SRLIW,
            SRAIW,
            LB,
            LH,
            LW,
            LBU,
            LHU,
            LD,
            SB,
            SH,
            SW,
            SD,
            JAL,
            J,
            RET,
            LUI,
            AUIPC,
            LLA,
            MUL,
            MULW,
            MULH,
            MULHSU,
            MULHU,
            DIV,
            DIVW,
            DIVU,
            REM,
            REMW,
            REMU,
            LR,
            SC,
            AMOSWAP,
            AMOADD,
            AMOAND,
            AMOOR,
            AMOXOR,
            FLW,
            FSW,
            LoadImm12,
            LoadImm32,
            LoadImm64,
            MV,

    RISCVInstEnd
};

TargetInstInfo& getRISCVInstInfo();

RISCV_NAMESPACE_END