version: "1.0"
name: master-pipeline
displayName: MasterPipeline
stages:
  - name: BuildAndTest
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: execute@docker
        name: execute_by_docker
        displayName: 基于镜像的脚本执行
        certificate: ""
        image: ubuntu:20.04
        command:
          - "# 请在此输入您想执行的脚本"
          - echo 'Hello Gitee!'
          - sudo apt-get update
          - sudo apt-get install -y build-essential uuid-dev libutfcpp-dev pkg-config make git cmake openjdk-11-jre
          - cmake -S . -B build
          - cmake --build build -j4
          - ./test.sh -t ./test/2021/functional/001_var_defn.sy
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./build
        notify: []
        strategy:
          retry: "0"
triggers:
  push:
    branches:
      include:
        - master
